即席麺とうどん・そうめん・そばの、日本から各国への販売実績金額の相関

In [1]:
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\natsu\anaconda3\lib\site-packages (2.0.2)

In [2]:
conda install xlrd

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda

In [3]:
conda install openpyxl

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda

In [4]:
import pandas as pd
df=pd.read_excel(r'C:\Users\natsu\myworks_for_GitHub\Python-machine-learning-study-log\opendata_analysis\datafiles\k002-2022-00-b025.xls')

In [5]:
display(df.head(10))

,報告書名：農林水産物品目別実績（輸出）,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,年次：令.４（２０２２）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,月次：年計,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,即席麺、うどん・そうめん・そば,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,国 名,即席麺,NaN,NaN,NaN,NaN,うどん・そうめん・そば,NaN,NaN,NaN,NaN
6,NaN,第一単位,第一数量,第二単位,第二数量,金額（千円）,第一単位,第一数量,第二単位,第二数量,金額（千円）
7,世界,NaN,0,KG,12698888,10047706,NaN,0,KG,11989825,4196139
8,大韓民国,NaN,0,KG,325081,298742,NaN,0,KG,362861,160653
9,中華人民共和国,NaN,0,KG,445577,499309,NaN,0,KG,1146219,560262

In [6]:
df2=df.drop(index=range(0,5),axis=0)

col=['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9']
df2=df2.drop(columns=col,axis=1)

In [7]:
df2 = df2.rename(columns={'報告書名：農林水産物品目別実績（輸出）':'国名'})
df2 = df2.rename(columns={'Unnamed: 5':'即席麺　売上金額(千円)'})
df2 = df2.rename(columns={'Unnamed: 10':'うどん・そば・そうめん　売上金額(千円)'})

In [8]:
display(df2.head(10))

         国名 即席麺　売上金額(千円) うどん・そば・そうめん　売上金額(千円)
5       国　名          NaN                  NaN
6       NaN       金額（千円）               金額（千円）
7        世界     10047706              4196139
8      大韓民国       298742               160653
9   中華人民共和国       499309               560262
10       台湾      1015745               284189
11     モンゴル         9960                 7218
12       香港      2793666               830895
13     ベトナム       506518                77954
14       タイ       202489               108394

In [9]:
tmp=df2.isnull()
tmp.sum()

国名                       1
即席麺　売上金額(千円)             9
うどん・そば・そうめん　売上金額(千円)    12
dtype: int64

In [10]:
df2.count()

国名                      75
即席麺　売上金額(千円)            67
うどん・そば・そうめん　売上金額(千円)    64
dtype: int64

In [11]:
df2.index=df2['国名']

In [12]:
df2.head(10)

              国名 即席麺　売上金額(千円) うどん・そば・そうめん　売上金額(千円)
国名
国　名          国　名          NaN                  NaN
NaN          NaN       金額（千円）               金額（千円）
世界            世界     10047706              4196139
大韓民国        大韓民国       298742               160653
中華人民共和国  中華人民共和国       499309               560262
台湾            台湾      1015745               284189
モンゴル        モンゴル         9960                 7218
香港            香港      2793666               830895
ベトナム        ベトナム       506518                77954
タイ            タイ       202489               108394

In [13]:
df3=df2.fillna(df2.mean)