In [8]:
'''
＜分析の流れ＞

SQLによりデータベースの前処理
↓
pandasによりデータの前処理
↓
統計解析
'''

'\n＜分析の流れ＞\n\nSQLによりデータベースの前処理\n↓\npandasによりデータの前処理\n↓\n統計解析\n'

In [9]:
'''
SQLによりデータベースの前処理をする。
'''

'\nSQLによりデータベースの前処理をする。\n'

In [10]:
import pandas as pd

In [11]:
#SQLとの連携
from getpass import getpass
from sqlalchemy import create_engine, text

password = getpass("MySQL password: ")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/pakistan_ecommerce"
)

In [12]:
query = """
-- データベース内のテーブルを確認
SHOW TABLES;
"""
df = pd.read_sql(query, engine)
display(df)

  Tables_in_pakistan_ecommerce
0             ecommerce_orders

In [13]:
query = """
-- データ件数を確認
SELECT COUNT(*)
FROM ecommerce_orders;
"""
df = pd.read_sql(query, engine)
display(df)

   COUNT(*)
0   1048575

In [14]:
#テーブルをデータフレームに変更
query = """
SELECT *
FROM ecommerce_orders
"""
df = pd.read_sql(query, engine)

In [15]:
print(df.columns)

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1',
       'sales_commission_code', 'discount_amount', 'payment_method',
       'working_date', 'bi_status', 'mv', 'year', 'month', 'customer_since',
       'm_y', 'fy', 'customer_id'],
      dtype='object')

In [16]:
#どのような要素があるか確認
for c in df.columns:
    display(c)
    display(df[c].unique())

'item_id'

array([211131, 211133, 211134, ..., 905207, 905208,      0],
      shape=(584525,))

'status'

array(['complete', 'canceled', 'order_refunded', 'received', 'refund',
       'closed', 'fraud', 'holded', 'exchange', 'pending_paypal', 'paid',
       None, 'cod', 'pending', '', 'processing', 'payment_review'],
      dtype=object)

'created_at'

array(['7/1/2016', '7/2/2016', '7/3/2016', '7/4/2016', '7/5/2016',
       '7/6/2016', '7/7/2016', '7/8/2016', '7/9/2016', '7/10/2016',
       '7/11/2016', '7/12/2016', '7/13/2016', '7/14/2016', '7/15/2016',
       '7/16/2016', '7/17/2016', '7/18/2016', '7/19/2016', '7/20/2016',
       '7/21/2016', '7/22/2016', '7/23/2016', '7/24/2016', '7/25/2016',
       '7/26/2016', '7/27/2016', '7/28/2016', '7/29/2016', '7/30/2016',
       '7/31/2016', '8/1/2016', '8/2/2016', '8/3/2016', '8/4/2016',
       '8/5/2016', '8/6/2016', '8/7/2016', '8/8/2016', '8/9/2016',
       '8/10/2016', '8/11/2016', '8/12/2016', '8/13/2016', '8/14/2016',
       '8/15/2016', '8/16/2016', '8/17/2016', '8/18/2016', '8/19/2016',
       '8/20/2016', '8/21/2016', '8/22/2016', '8/23/2016', '8/24/2016',
       '8/25/2016', '8/26/2016', '8/27/2016', '8/28/2016', '8/29/2016',
       '8/30/2016', '8/31/2016', '9/1/2016', '9/2/2016', '9/3/2016',
       '9/4/2016', '9/5/2016', '9/6/2016', '9/7/2016', '9/8/2016',
       '9/9/2016', '9/10/2016', '9/11/2016', '9/12/2016', '9/13/2016',
       '9/14/2016', '9/15/2016', '9/16/2016', '9/17/2016', '9/18/2016',
       '9/19/2016', '9/20/2016', '9/21/2016', '9/22/2016', '9/23/2016',
       '9/24/2016', '9/25/2016', '9/26/2016', '9/27/2016', '9/28/2016',
       '9/29/2016', '9/30/2016', '10/1/2016', '10/2/2016', '10/3/2016',
       '10/4/2016', '10/5/2016', '10/6/2016', '10/7/2016', '10/8/2016',
       '10/9/2016', '10/10/2016', '10/11/2016', '10/12/2016',
       '10/13/2016', '10/14/2016', '10/15/2016', '10/16/2016',
       '10/17/2016', '10/18/2016', '10/19/2016', '10/20/2016',
       '10/21/2016', '10/22/2016', '10/23/2016', '10/24/2016',
       '10/25/2016', '10/26/2016', '10/27/2016', '10/28/2016',
       '10/29/2016', '10/30/2016', '10/31/2016', '11/1/2016', '11/2/2016',
       '11/3/2016', '11/4/2016', '11/5/2016', '11/6/2016', '11/7/2016',
       '11/8/2016', '11/9/2016', '11/10/2016', '11/11/2016', '11/12/2016',
       '11/13/2016', '11/14/2016', '11/15/2016', '11/16/2016',
       '11/17/2016', '11/18/2016', '11/19/2016', '11/20/2016',
       '11/21/2016', '11/22/2016', '11/23/2016', '11/24/2016',
       '11/25/2016', '11/26/2016', '11/27/2016', '11/28/2016',
       '11/29/2016', '11/30/2016', '12/1/2016', '12/2/2016', '12/3/2016',
       '12/4/2016', '12/5/2016', '12/6/2016', '12/7/2016', '12/8/2016',
       '12/9/2016', '12/10/2016', '12/11/2016', '12/12/2016',
       '12/13/2016', '12/14/2016', '12/15/2016', '12/16/2016',
       '12/17/2016', '12/18/2016', '12/19/2016', '12/20/2016',
       '12/21/2016', '12/22/2016', '12/23/2016', '12/24/2016',
       '12/25/2016', '12/26/2016', '12/27/2016', '12/28/2016',
       '12/29/2016', '12/30/2016', '12/31/2016', '1/1/2017', '1/2/2017',
       '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017', '1/7/2017',
       '1/8/2017', '1/9/2017', '1/10/2017', '1/11/2017', '1/12/2017',
       '1/13/2017', '1/14/2017', '1/15/2017', '1/16/2017', '1/17/2017',
       '1/18/2017', '1/19/2017', '1/20/2017', '1/21/2017', '1/22/2017',
       '1/23/2017', '1/24/2017', '1/25/2017', '1/26/2017', '1/27/2017',
       '1/28/2017', '1/29/2017', '1/30/2017', '1/31/2017', '2/1/2017',
       '2/2/2017', '2/3/2017', '2/4/2017', '2/5/2017', '2/6/2017',
       '2/7/2017', '2/8/2017', '2/9/2017', '2/10/2017', '2/11/2017',
       '2/12/2017', '2/13/2017', '2/14/2017', '2/15/2017', '2/16/2017',
       '2/17/2017', '2/18/2017', '2/19/2017', '2/20/2017', '2/21/2017',
       '2/22/2017', '2/23/2017', '2/24/2017', '2/25/2017', '2/26/2017',
       '2/27/2017', '2/28/2017', '3/1/2017', '3/2/2017', '3/3/2017',
       '3/4/2017', '3/5/2017', '3/6/2017', '3/7/2017', '3/8/2017',
       '3/9/2017', '3/10/2017', '3/11/2017', '3/12/2017', '3/13/2017',
       '3/14/2017', '3/15/2017', '3/16/2017', '3/17/2017', '3/18/2017',
       '3/19/2017', '3/20/2017', '3/21/2017', '3/22/2017', '3/23/2017',
       '3/24/2017', '3/25/2017', '3/26/2017', '3/27/2017', '3/28/2017',
       '3/29/2017', '3/30/2017', '3/31/2017', '4/1/2017', '4/2/2017',
       '4/3/2017', '4/4/2017', '4/5/2017', '4/6/2017', '4/7/2017',
       '4/8/2017', '4/9/2017', '4/10/2017', '4/11/2017', '4/12/2017',
       '4/13/2017', '4/14/2017', '4/15/2017', '4/16/2017', '4/17/2017',
       '4/18/2017', '4/19/2017', '4/20/2017', '4/21/2017', '4/22/2017',
       '4/23/2017', '4/24/2017', '4/25/2017', '4/26/2017', '4/27/2017',
       '4/28/2017', '4/29/2017', '4/30/2017', '5/1/2017', '5/2/2017',
       '5/3/2017', '5/4/2017', '5/5/2017', '5/6/2017', '5/7/2017',
       '5/8/2017', '5/9/2017', '5/10/2017', '5/11/2017', '5/12/2017',
       '5/13/2017', '5/14/2017', '5/15/2017', '5/16/2017', '5/17/2017',
       '5/18/2017', '5/19/2017', '5/20/2017', '5/21/2017', '5/22/2017',
       '5/23/2017', '5/24/2017', '5/25/2017', '5/26/2017', '5/27/2017',
       '5/28/2017', '5/29/2017', '5/30/2017', '5/31/2017', '6/1/2017',
       '6/2/2017', '6/3/2017', '6/4/2017', '6/5/2017', '6/6/2017',
       '6/7/2017', '6/8/2017', '6/9/2017', '6/10/2017', '6/11/2017',
       '6/12/2017', '6/13/2017', '6/14/2017', '6/15/2017', '6/16/2017',
       '6/17/2017', '6/18/2017', '6/19/2017', '6/20/2017', '6/21/2017',
       '6/22/2017', '6/23/2017', '6/24/2017', '6/25/2017', '6/26/2017',
       '6/27/2017', '6/28/2017', '6/29/2017', '6/30/2017', '7/1/2017',
       '7/2/2017', '7/3/2017', '7/4/2017', '7/5/2017', '7/6/2017',
       '7/7/2017', '7/8/2017', '7/9/2017', '7/10/2017', '7/11/2017',
       '7/12/2017', '7/13/2017', '7/14/2017', '7/15/2017', '7/16/2017',
       '7/17/2017', '7/18/2017', '7/19/2017', '7/20/2017', '7/21/2017',
       '7/22/2017', '7/23/2017', '7/24/2017', '7/25/2017', '7/26/2017',
       '7/27/2017', '7/28/2017', '7/29/2017', '7/30/2017', '7/31/2017',
       '8/1/2017', '8/2/2017', '8/3/2017', '8/4/2017', '8/5/2017',
       '8/6/2017', '8/7/2017', '8/8/2017', '8/9/2017', '8/10/2017',
       '8/11/2017', '8/12/2017', '8/13/2017', '8/14/2017', '8/15/2017',
       '8/16/2017', '8/17/2017', '8/18/2017', '8/19/2017', '8/20/2017',
       '8/21/2017', '8/22/2017', '8/23/2017', '8/24/2017', '8/25/2017',
       '8/26/2017', '8/27/2017', '8/28/2017', '8/29/2017', '8/30/2017',
       '8/31/2017', '9/1/2017', '9/2/2017', '9/3/2017', '9/4/2017',
       '9/5/2017', '9/6/2017', '9/7/2017', '9/8/2017', '9/9/2017',
       '9/10/2017', '9/11/2017', '9/12/2017', '9/13/2017', '9/14/2017',
       '9/15/2017', '9/16/2017', '9/17/2017', '9/18/2017', '9/19/2017',
       '9/20/2017', '9/21/2017', '9/22/2017', '9/23/2017', '9/24/2017',
       '9/25/2017', '9/26/2017', '9/27/2017', '9/28/2017', '9/29/2017',
       '9/30/2017', '10/1/2017', '10/2/2017', '10/3/2017', '10/4/2017',
       '10/5/2017', '10/6/2017', '10/7/2017', '10/8/2017', '10/9/2017',
       '10/10/2017', '10/11/2017', '10/12/2017', '10/13/2017',
       '10/14/2017', '10/15/2017', '10/16/2017', '10/17/2017',
       '10/18/2017', '10/19/2017', '10/20/2017', '10/21/2017',
       '10/22/2017', '10/23/2017', '10/24/2017', '10/25/2017',
       '10/26/2017', '10/27/2017', '10/28/2017', '10/29/2017',
       '10/30/2017', '10/31/2017', '11/1/2017', '11/2/2017', '11/3/2017',
       '11/4/2017', '11/5/2017', '11/6/2017', '11/7/2017', '11/8/2017',
       '11/9/2017', '11/10/2017', '11/11/2017', '11/12/2017',
       '11/13/2017', '11/14/2017', '11/15/2017', '11/16/2017',
       '11/17/2017', '11/18/2017', '11/19/2017', '11/20/2017',
       '11/21/2017', '11/22/2017', '11/23/2017', '11/24/2017',
       '11/25/2017', '11/26/2017', '11/27/2017', '11/28/2017',
       '11/29/2017', '11/30/2017', '12/1/2017', '12/2/2017', '12/3/2017',
       '12/4/2017', '12/5/2017', '12/6/2017', '12/7/2017', '12/8/2017',
       '12/9/2017', '12/10/2017', '12/11/2017', '12/12/2017',
       '12/13/2017', '12/14/2017', '12/15/2017', '12/16/2017',
       '12/17/2017', '12/18/2017', '12/19/2017', '12/20/2017',
       '12/21/2017', '12/22/2017', '12/23/2017', '12/24/2017',
       '12/25/2017', '12/26/2017', '12/27/2017', '12/28/2017',
       '12/29/2017', '12/30/2017', '12/31/2017', '2/23/2018', '1/1/2018',
       '1/2/2018', '1/3/2018', '1/4/2018', '1/5/2018', '1/6/2018',
       '1/7/2018', '1/8/2018', '1/9/2018', '1/10/2018', '1/11/2018',
       '1/12/2018', '1/13/2018', '1/14/2018', '1/15/2018', '1/16/2018',
       '1/17/2018', '1/18/2018', '1/19/2018', '1/20/2018', '1/21/2018',
       '1/22/2018', '1/23/2018', '1/24/2018', '1/25/2018', '1/26/2018',
       '1/27/2018', '1/28/2018', '1/29/2018', '1/30/2018', '1/31/2018',
       '2/1/2018', '2/2/2018', '2/3/2018', '2/4/2018', '2/5/2018',
       '2/6/2018', '2/7/2018', '2/8/2018', '2/9/2018', '2/10/2018',
       '2/11/2018', '2/12/2018', '2/13/2018', '2/14/2018', '2/15/2018',
       '2/16/2018', '2/17/2018', '2/18/2018', '2/19/2018', '2/20/2018',
       '2/21/2018', '2/22/2018', '2/24/2018', '2/25/2018', '2/26/2018',
       '2/27/2018', '2/28/2018', '3/1/2018', '3/2/2018', '3/3/2018',
       '3/4/2018', '3/5/2018', '3/6/2018', '3/7/2018', '3/8/2018',
       '3/9/2018', '3/10/2018', '3/11/2018', '3/12/2018', '3/13/2018',
       '3/14/2018', '3/15/2018', '3/29/2018', '3/16/2018', '3/17/2018',
       '3/18/2018', '3/19/2018', '3/20/2018', '3/21/2018', '3/22/2018',
       '3/23/2018', '3/24/2018', '3/25/2018', '3/26/2018', '3/27/2018',
       '3/28/2018', '3/30/2018', '3/31/2018', '4/1/2018', '4/2/2018',
       '4/3/2018', '4/4/2018', '4/5/2018', '4/6/2018', '4/7/2018',
       '4/8/2018', '4/9/2018', '4/10/2018', '4/11/2018', '4/12/2018',
       '4/13/2018', '4/14/2018', '4/15/2018', '4/16/2018', '4/17/2018',
       '4/18/2018', '4/19/2018', '4/20/2018', '4/21/2018', '4/22/2018',
       '4/23/2018', '4/24/2018', '4/25/2018', '4/26/2018', '4/27/2018',
       '4/28/2018', '4/29/2018', '4/30/2018', '5/1/2018', '5/2/2018',
       '5/3/2018', '5/4/2018', '5/5/2018', '5/6/2018', '5/7/2018',
       '5/8/2018', '5/9/2018', '5/10/2018', '5/11/2018', '5/12/2018',
       '5/13/2018', '5/14/2018', '5/15/2018', '5/16/2018', '5/17/2018',
       '5/18/2018', '5/19/2018', '5/20/2018', '5/21/2018', '5/22/2018',
       '5/23/2018', '5/24/2018', '5/25/2018', '5/26/2018', '5/27/2018',
       '5/28/2018', '5/29/2018', '5/30/2018', '5/31/2018', '6/1/2018',
       '6/2/2018', '6/3/2018', '6/4/2018', '6/5/2018', '6/6/2018',
       '6/7/2018', '6/8/2018', '6/9/2018', '6/10/2018', '6/11/2018',
       '6/12/2018', '6/13/2018', '6/14/2018', '6/15/2018', '6/16/2018',
       '6/17/2018', '6/18/2018', '6/19/2018', '6/20/2018', '6/21/2018',
       '6/22/2018', '6/23/2018', '6/24/2018', '6/25/2018', '6/26/2018',
       '6/27/2018', '6/28/2018', '7/2/2018', '6/29/2018', '6/30/2018',
       '7/1/2018', '7/3/2018', '7/4/2018', '7/5/2018', '7/6/2018',
       '7/7/2018', '7/8/2018', '7/9/2018', '7/10/2018', '7/11/2018',
       '7/12/2018', '7/13/2018', '7/14/2018', '7/15/2018', '7/16/2018',
       '7/17/2018', '7/18/2018', '7/19/2018', '7/20/2018', '7/21/2018',
       '7/22/2018', '7/23/2018', '7/24/2018', '7/25/2018', '7/26/2018',
       '7/27/2018', '7/28/2018', '7/29/2018', '7/30/2018', '7/31/2018',
       '8/1/2018', '8/2/2018', '8/3/2018', '8/4/2018', '8/5/2018',
       '8/6/2018', '8/7/2018', '8/8/2018', '8/9/2018', '8/10/2018',
       '8/11/2018', '8/12/2018', '8/13/2018', '8/14/2018', '8/15/2018',
       '8/16/2018', '8/17/2018', '8/18/2018', '8/19/2018', '8/20/2018',
       '8/21/2018', '8/22/2018', '8/23/2018', '8/24/2018', '8/25/2018',
       '8/26/2018', '8/27/2018', '8/28/2018', ''], dtype=object)

'sku'

array(['kreations_YI 06-L',
       'kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Body Spray Free',
       'Ego_UP0017-999-MR0', ..., 'WOFVAL59D5EA84167F9-M',
       'WOFNIG5B4D7EB0E9FDD-L', 'WOFSCE5AE00357AECDE'],
      shape=(84890,), dtype=object)

'price'

array([ 1950.,   240.,  2450., ...,  8165., 22950.,  8344.], shape=(9121,))

'qty_ordered'

array([   1.,    2.,    5.,    3.,    4.,    6.,   10.,   34.,    9.,
          7.,   14.,   11.,   15.,    8.,   20.,   27.,   12.,   13.,
        130.,   16.,   40.,  100.,   50.,  120.,   25.,   22.,  200.,
         31.,   97.,   35.,  119.,   24.,   99.,   38.,   30.,   26.,
         48.,   19.,   32.,   28.,   37.,   18.,  150.,  300.,   21.,
         49.,   17.,   45.,   36.,   56.,   72.,  502.,   33.,   29.,
        304., 1000.,   52.,  125.,  141.,  180.,  186.,   96.,  187.,
        144.,   66.,   60.,  185.,   90.,   70.,   23.,  102.,  500.,
        380.,   75.,    0.])

'grand_total'

array([1.95000e+03, 2.40000e+02, 2.45000e+03, ..., 5.93000e+03,
       2.35100e+04, 6.52178e+05], shape=(36813,))

'increment_id'

array(['100147443', '100147444', '100147445', ..., '100562386',
       '100562387', ''], shape=(408783,), dtype=object)

'category_name_1'

array(["Women's Fashion", 'Beauty & Grooming', 'Soghaat',
       'Mobiles & Tablets', 'Appliances', 'Home & Living',
       "Men's Fashion", 'Kids & Baby', None, 'Others', 'Entertainment',
       'Computing', 'Superstore', 'Health & Sports', 'Books',
       'School & Education', ''], dtype=object)

'sales_commission_code'

array([None, 'R-FSD-52352', '105259', ..., 'GRS-4090974-1',
       'GRS-4090975-1', '100559728'], shape=(7228,), dtype=object)

'discount_amount'

array([  0.  , 300.  ,  82.5 , ..., 381.38, 634.13, 355.35],
      shape=(25223,))

'payment_method'

array(['cod', 'ublcreditcard', 'mygateway', 'customercredit',
       'cashatdoorstep', 'mcblite', 'internetbanking', 'marketingexpense',
       'productcredit', 'financesettlement', 'Payaxis', 'jazzvoucher',
       'jazzwallet', 'Easypay', 'Easypay_MA', 'easypay_voucher',
       'bankalfalah', 'apg', ''], dtype=object)

'working_date'

array(['7/1/2016', '7/2/2016', '7/3/2016', '7/4/2016', '7/5/2016',
       '7/6/2016', '7/7/2016', '7/8/2016', '7/9/2016', '7/10/2016',
       '7/11/2016', '7/12/2016', '7/13/2016', '7/14/2016', '7/15/2016',
       '7/16/2016', '7/17/2016', '7/18/2016', '7/19/2016', '7/20/2016',
       '7/21/2016', '7/22/2016', '7/23/2016', '7/24/2016', '7/25/2016',
       '7/26/2016', '7/27/2016', '7/28/2016', '7/29/2016', '7/30/2016',
       '7/31/2016', '8/1/2016', '8/2/2016', '8/3/2016', '8/4/2016',
       '8/5/2016', '8/6/2016', '8/7/2016', '8/8/2016', '8/9/2016',
       '8/10/2016', '8/11/2016', '8/12/2016', '8/13/2016', '8/14/2016',
       '8/15/2016', '8/16/2016', '8/17/2016', '8/18/2016', '8/19/2016',
       '8/20/2016', '8/21/2016', '8/22/2016', '8/23/2016', '8/24/2016',
       '8/25/2016', '8/26/2016', '8/27/2016', '8/28/2016', '8/29/2016',
       '8/30/2016', '8/31/2016', '9/1/2016', '9/2/2016', '9/3/2016',
       '9/4/2016', '9/5/2016', '9/6/2016', '9/7/2016', '9/8/2016',
       '9/9/2016', '9/10/2016', '9/11/2016', '9/12/2016', '9/13/2016',
       '9/14/2016', '9/15/2016', '9/16/2016', '9/17/2016', '9/18/2016',
       '9/19/2016', '9/20/2016', '9/21/2016', '9/22/2016', '9/23/2016',
       '9/24/2016', '9/25/2016', '9/26/2016', '9/27/2016', '9/28/2016',
       '9/29/2016', '9/30/2016', '10/1/2016', '10/2/2016', '10/3/2016',
       '10/4/2016', '10/5/2016', '10/6/2016', '10/7/2016', '10/8/2016',
       '10/9/2016', '10/10/2016', '10/11/2016', '10/12/2016',
       '10/13/2016', '10/14/2016', '10/15/2016', '10/16/2016',
       '10/17/2016', '10/18/2016', '10/19/2016', '10/20/2016',
       '10/21/2016', '10/22/2016', '10/23/2016', '10/24/2016',
       '10/25/2016', '10/26/2016', '10/27/2016', '10/28/2016',
       '10/29/2016', '10/30/2016', '10/31/2016', '11/1/2016', '11/2/2016',
       '11/3/2016', '11/4/2016', '11/5/2016', '11/6/2016', '11/7/2016',
       '11/8/2016', '11/9/2016', '11/10/2016', '11/11/2016', '11/12/2016',
       '11/13/2016', '11/14/2016', '11/15/2016', '11/16/2016',
       '11/17/2016', '11/18/2016', '11/19/2016', '11/20/2016',
       '11/21/2016', '11/22/2016', '11/23/2016', '11/24/2016',
       '11/25/2016', '11/26/2016', '11/27/2016', '11/28/2016',
       '11/29/2016', '11/30/2016', '12/1/2016', '12/2/2016', '12/3/2016',
       '12/4/2016', '12/5/2016', '12/6/2016', '12/7/2016', '12/8/2016',
       '12/9/2016', '12/10/2016', '12/11/2016', '12/12/2016',
       '12/13/2016', '12/14/2016', '12/15/2016', '12/16/2016',
       '12/17/2016', '12/18/2016', '12/19/2016', '12/20/2016',
       '12/21/2016', '12/22/2016', '12/23/2016', '12/24/2016',
       '12/25/2016', '12/26/2016', '12/27/2016', '12/28/2016',
       '12/29/2016', '12/30/2016', '12/31/2016', '1/1/2017', '1/2/2017',
       '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017', '1/7/2017',
       '1/8/2017', '1/9/2017', '1/10/2017', '1/11/2017', '1/12/2017',
       '1/13/2017', '1/14/2017', '1/15/2017', '1/16/2017', '1/17/2017',
       '1/18/2017', '1/19/2017', '1/20/2017', '1/21/2017', '1/22/2017',
       '1/23/2017', '1/24/2017', '1/25/2017', '1/26/2017', '1/27/2017',
       '1/28/2017', '1/29/2017', '1/30/2017', '1/31/2017', '2/1/2017',
       '2/2/2017', '2/3/2017', '2/4/2017', '2/5/2017', '2/6/2017',
       '2/7/2017', '2/8/2017', '2/9/2017', '2/10/2017', '2/11/2017',
       '2/12/2017', '2/13/2017', '2/14/2017', '2/15/2017', '2/16/2017',
       '2/17/2017', '2/18/2017', '2/19/2017', '2/20/2017', '2/21/2017',
       '2/22/2017', '2/23/2017', '2/24/2017', '2/25/2017', '2/26/2017',
       '2/27/2017', '2/28/2017', '3/1/2017', '3/2/2017', '3/3/2017',
       '3/4/2017', '3/5/2017', '3/6/2017', '3/7/2017', '3/8/2017',
       '3/9/2017', '3/10/2017', '3/11/2017', '3/12/2017', '3/13/2017',
       '3/14/2017', '3/15/2017', '3/16/2017', '3/17/2017', '3/18/2017',
       '3/19/2017', '3/20/2017', '3/21/2017', '3/22/2017', '3/23/2017',
       '3/24/2017', '3/25/2017', '3/26/2017', '3/27/2017', '3/28/2017',
       '3/29/2017', '3/30/2017', '3/31/2017', '4/1/2017', '4/2/2017',
       '4/3/2017', '4/4/2017', '4/5/2017', '4/6/2017', '4/7/2017',
       '4/8/2017', '4/9/2017', '4/10/2017', '4/11/2017', '4/12/2017',
       '4/13/2017', '4/14/2017', '4/15/2017', '4/16/2017', '4/17/2017',
       '4/18/2017', '4/19/2017', '4/20/2017', '4/21/2017', '4/22/2017',
       '4/23/2017', '4/24/2017', '4/25/2017', '4/26/2017', '4/27/2017',
       '4/28/2017', '4/29/2017', '4/30/2017', '5/1/2017', '5/2/2017',
       '5/3/2017', '5/4/2017', '5/5/2017', '5/6/2017', '5/7/2017',
       '5/8/2017', '5/9/2017', '5/10/2017', '5/11/2017', '5/12/2017',
       '5/13/2017', '5/14/2017', '5/15/2017', '5/16/2017', '5/17/2017',
       '5/18/2017', '5/19/2017', '5/20/2017', '5/21/2017', '5/22/2017',
       '5/23/2017', '5/24/2017', '5/25/2017', '5/26/2017', '5/27/2017',
       '5/28/2017', '5/29/2017', '5/30/2017', '5/31/2017', '6/1/2017',
       '6/2/2017', '6/3/2017', '6/4/2017', '6/5/2017', '6/6/2017',
       '6/7/2017', '6/8/2017', '6/9/2017', '6/10/2017', '6/11/2017',
       '6/12/2017', '6/13/2017', '6/14/2017', '6/15/2017', '6/16/2017',
       '6/17/2017', '6/18/2017', '6/19/2017', '6/20/2017', '6/21/2017',
       '6/22/2017', '6/23/2017', '6/24/2017', '6/25/2017', '6/26/2017',
       '6/27/2017', '6/28/2017', '6/29/2017', '6/30/2017', '7/1/2017',
       '7/2/2017', '7/3/2017', '7/4/2017', '7/5/2017', '7/6/2017',
       '7/7/2017', '7/8/2017', '7/9/2017', '7/10/2017', '7/11/2017',
       '7/12/2017', '7/13/2017', '7/14/2017', '7/15/2017', '7/16/2017',
       '7/17/2017', '7/18/2017', '7/19/2017', '7/20/2017', '7/21/2017',
       '7/22/2017', '7/23/2017', '7/24/2017', '7/25/2017', '7/26/2017',
       '7/27/2017', '7/28/2017', '7/29/2017', '7/30/2017', '7/31/2017',
       '8/1/2017', '8/2/2017', '8/3/2017', '8/4/2017', '8/5/2017',
       '8/6/2017', '8/7/2017', '8/8/2017', '8/9/2017', '8/10/2017',
       '8/11/2017', '8/12/2017', '8/13/2017', '8/14/2017', '8/15/2017',
       '8/16/2017', '8/17/2017', '8/18/2017', '8/19/2017', '8/20/2017',
       '8/21/2017', '8/22/2017', '8/23/2017', '8/24/2017', '8/25/2017',
       '8/26/2017', '8/27/2017', '8/28/2017', '8/29/2017', '8/30/2017',
       '8/31/2017', '9/1/2017', '9/2/2017', '9/3/2017', '9/4/2017',
       '9/5/2017', '9/6/2017', '9/7/2017', '9/8/2017', '9/9/2017',
       '9/10/2017', '9/11/2017', '9/12/2017', '9/13/2017', '9/14/2017',
       '9/15/2017', '9/16/2017', '9/17/2017', '9/18/2017', '9/19/2017',
       '9/20/2017', '9/21/2017', '9/22/2017', '9/23/2017', '9/24/2017',
       '9/25/2017', '9/26/2017', '9/27/2017', '9/28/2017', '9/29/2017',
       '9/30/2017', '10/1/2017', '10/2/2017', '10/3/2017', '10/4/2017',
       '10/5/2017', '10/6/2017', '10/7/2017', '10/8/2017', '10/9/2017',
       '10/10/2017', '10/11/2017', '10/12/2017', '10/13/2017',
       '10/14/2017', '10/15/2017', '10/16/2017', '10/17/2017',
       '10/18/2017', '10/19/2017', '10/20/2017', '10/21/2017',
       '10/22/2017', '10/23/2017', '10/24/2017', '10/25/2017',
       '10/26/2017', '10/27/2017', '10/28/2017', '10/29/2017',
       '10/30/2017', '10/31/2017', '11/1/2017', '11/2/2017', '11/3/2017',
       '11/4/2017', '11/5/2017', '11/6/2017', '11/7/2017', '11/8/2017',
       '11/9/2017', '11/10/2017', '11/11/2017', '11/12/2017',
       '11/13/2017', '11/14/2017', '11/15/2017', '11/16/2017',
       '11/17/2017', '11/18/2017', '11/19/2017', '11/20/2017',
       '11/21/2017', '11/22/2017', '11/23/2017', '11/24/2017',
       '11/25/2017', '11/26/2017', '11/27/2017', '11/28/2017',
       '11/29/2017', '11/30/2017', '12/1/2017', '12/2/2017', '12/3/2017',
       '12/4/2017', '12/5/2017', '12/6/2017', '12/7/2017', '12/8/2017',
       '12/9/2017', '12/10/2017', '12/11/2017', '12/12/2017',
       '12/13/2017', '12/14/2017', '12/15/2017', '12/16/2017',
       '12/17/2017', '12/18/2017', '12/19/2017', '12/20/2017',
       '12/21/2017', '12/22/2017', '12/23/2017', '12/24/2017',
       '12/25/2017', '12/26/2017', '12/27/2017', '12/28/2017',
       '12/29/2017', '12/30/2017', '12/31/2017', '2/23/2018', '1/1/2018',
       '1/2/2018', '1/3/2018', '1/4/2018', '1/5/2018', '1/6/2018',
       '1/7/2018', '1/8/2018', '1/9/2018', '1/10/2018', '1/11/2018',
       '1/12/2018', '1/13/2018', '1/14/2018', '1/15/2018', '1/16/2018',
       '1/17/2018', '1/18/2018', '1/19/2018', '1/20/2018', '1/21/2018',
       '1/22/2018', '1/23/2018', '1/24/2018', '1/25/2018', '1/26/2018',
       '1/27/2018', '1/28/2018', '1/29/2018', '1/30/2018', '1/31/2018',
       '2/1/2018', '2/2/2018', '2/3/2018', '2/4/2018', '2/5/2018',
       '2/6/2018', '2/7/2018', '2/8/2018', '2/9/2018', '2/10/2018',
       '2/11/2018', '2/12/2018', '2/13/2018', '2/14/2018', '2/15/2018',
       '2/16/2018', '2/17/2018', '2/18/2018', '2/19/2018', '2/20/2018',
       '2/21/2018', '2/22/2018', '2/24/2018', '2/25/2018', '2/26/2018',
       '2/27/2018', '2/28/2018', '3/1/2018', '3/2/2018', '3/3/2018',
       '3/4/2018', '3/5/2018', '3/6/2018', '3/7/2018', '3/8/2018',
       '3/9/2018', '3/10/2018', '3/11/2018', '3/12/2018', '3/13/2018',
       '3/14/2018', '3/15/2018', '3/29/2018', '3/16/2018', '3/17/2018',
       '3/18/2018', '3/19/2018', '3/20/2018', '3/21/2018', '3/22/2018',
       '3/23/2018', '3/24/2018', '3/25/2018', '3/26/2018', '3/27/2018',
       '3/28/2018', '3/30/2018', '3/31/2018', '4/1/2018', '4/2/2018',
       '4/3/2018', '4/4/2018', '4/5/2018', '4/6/2018', '4/7/2018',
       '4/8/2018', '4/9/2018', '4/10/2018', '4/11/2018', '4/12/2018',
       '4/13/2018', '4/14/2018', '4/15/2018', '4/16/2018', '4/17/2018',
       '4/18/2018', '4/19/2018', '4/20/2018', '4/21/2018', '4/22/2018',
       '4/23/2018', '4/24/2018', '4/25/2018', '4/26/2018', '4/27/2018',
       '4/28/2018', '4/29/2018', '4/30/2018', '5/1/2018', '5/2/2018',
       '5/3/2018', '5/4/2018', '5/5/2018', '5/6/2018', '5/7/2018',
       '5/8/2018', '5/9/2018', '5/10/2018', '5/11/2018', '5/12/2018',
       '5/13/2018', '5/14/2018', '5/15/2018', '5/16/2018', '5/17/2018',
       '5/18/2018', '5/19/2018', '5/20/2018', '5/21/2018', '5/22/2018',
       '5/23/2018', '5/24/2018', '5/25/2018', '5/26/2018', '5/27/2018',
       '5/28/2018', '5/29/2018', '5/30/2018', '5/31/2018', '6/1/2018',
       '6/2/2018', '6/3/2018', '6/4/2018', '6/5/2018', '6/6/2018',
       '6/7/2018', '6/8/2018', '6/9/2018', '6/10/2018', '6/11/2018',
       '6/12/2018', '6/13/2018', '6/14/2018', '6/15/2018', '6/16/2018',
       '6/17/2018', '6/18/2018', '6/19/2018', '6/20/2018', '6/21/2018',
       '6/22/2018', '6/23/2018', '6/24/2018', '6/25/2018', '6/26/2018',
       '6/27/2018', '6/28/2018', '7/2/2018', '6/29/2018', '6/30/2018',
       '7/1/2018', '7/3/2018', '7/4/2018', '7/5/2018', '7/6/2018',
       '7/7/2018', '7/8/2018', '7/9/2018', '7/10/2018', '7/11/2018',
       '7/12/2018', '7/13/2018', '7/14/2018', '7/15/2018', '7/16/2018',
       '7/17/2018', '7/18/2018', '7/19/2018', '7/20/2018', '7/21/2018',
       '7/22/2018', '7/23/2018', '7/24/2018', '7/25/2018', '7/26/2018',
       '7/27/2018', '7/28/2018', '7/29/2018', '7/30/2018', '7/31/2018',
       '8/1/2018', '8/2/2018', '8/3/2018', '8/4/2018', '8/5/2018',
       '8/6/2018', '8/7/2018', '8/8/2018', '8/9/2018', '8/10/2018',
       '8/11/2018', '8/12/2018', '8/13/2018', '8/14/2018', '8/15/2018',
       '8/16/2018', '8/17/2018', '8/18/2018', '8/19/2018', '8/20/2018',
       '8/21/2018', '8/22/2018', '8/23/2018', '8/24/2018', '8/25/2018',
       '8/26/2018', '8/27/2018', '8/28/2018', ''], dtype=object)

'bi_status'

array(['#REF!', 'Gross', 'Net', 'Valid', ''], dtype=object)

'mv'

array([' 1,950 ', ' 240 ', ' 2,450 ', ..., ' 8,165 ', ' 8,344 ', ''],
      shape=(9721,), dtype=object)

'year'

array([2016, 2017, 2018,    0])

'month'

array([ 7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  0])

'customer_since'

array(['2016-7', '2016-8', '2016-9', '2016-10', '2016-11', '2016-12',
       '2017-1', '2017-2', '2017-3', '2017-4', '2017-5', '2017-6',
       '2017-7', '2017-8', '2017-9', '2017-10', '2017-11', '2017-12',
       '2018-1', '#N/A', '2018-2', '2018-3', '2018-4', '2018-5', '2018-6',
       '2018-7', '2018-8', ''], dtype=object)

'm_y'

array(['7-2016', '8-2016', '9-2016', '10-2016', '11-2016', '12-2016',
       '1-2017', '2-2017', '3-2017', '4-2017', '5-2017', '6-2017',
       '7-2017', '8-2017', '9-2017', '10-2017', '11-2017', '12-2017',
       '2-2018', '1-2018', '3-2018', '4-2018', '5-2018', '6-2018',
       '7-2018', '8-2018', ''], dtype=object)

'fy'

array(['FY17', 'FY18', 'FY19', ''], dtype=object)

'customer_id'

array([     1,      2,      3, ..., 115324, 115325, 115326],
      shape=(115327,))

In [22]:
for c in df.columns:
    print(f'{df[c].dtype} = {c}列のデータ型')

int64 = item_id列のデータ型
object = status列のデータ型
object = created_at列のデータ型
object = sku列のデータ型
float64 = price列のデータ型
float64 = qty_ordered列のデータ型
float64 = grand_total列のデータ型
object = increment_id列のデータ型
object = category_name_1列のデータ型
object = sales_commission_code列のデータ型
float64 = discount_amount列のデータ型
object = payment_method列のデータ型
object = working_date列のデータ型
object = bi_status列のデータ型
object = mv列のデータ型
int64 = year列のデータ型
int64 = month列のデータ型
object = customer_since列のデータ型
object = m_y列のデータ型
object = fy列のデータ型
int64 = customer_id列のデータ型

In [ ]:
'''
(kaggleのデータセットの説明で各列について十分な説明がなされていなかったため、ChatGPTにサイトを読み込ませ、列の内容を推測させた)
| `item_id`               | 商品・明細を識別するID         
| `status`                | 注文のステータス           
| `created_at`            | 注文が作成された日時            
| `sku`                   | 商品を識別するSKU                
| `price`                 | 商品単価                        
| `qty_ordered`           | 注文数量       
| `grand_total`           | 注文・明細の合計金額      
| `category_name_1`       | 商品カテゴリ          
| `sales_commission_code` | 販売者・販売に関するコミッションコード        
| `discount_amount`       | 割引額 
| `payment_method`        | 支払方法   
| `Working.Date`          | 業務上の処理日                      
| `BI.Status`             | BI（Business Intelligence）上の分類 
| `MV`                    | Market Value / 市場価値と考えられる価格情報
| `Year`                  | `created_at`から作られた年
| `Month`                 | `created_at`から作られた月
| `Customer.Since`        | 顧客が初めて利用した時期 
| `M.Y`                   | 月・年を表す加工済み日付   
| `FY`                    | Fiscal Year（会計年度）   
| `Customer.ID`           | 顧客ID              
'''

In [ ]:
'''
分析の指針を整理する。

＜目的＞
データの分析により、新たな知見を見つけ出し、商品の売り上げを向上させること。


＜分析内容＞
・商品カテゴリーごとの分析
・支払方法ごとの変化
・利益が最も大きいカテゴリー
・顧客分析、ペルソナの考察
・時期ごとの注文カテゴリの傾向分析

したがって、下記のような分析が候補として考えられる。
・売上に影響している要因は何か（回帰）
・利益を出す商品・出さない商品を予測する（分類）
・ペルソナの推定（クラスタリング、分類）

今回は回帰分析の練習として、「売上に影響している要因は何か（回帰）」に絞って分析を行う。

今回のデータセットでは、mv(市場価値)は明らかにされているものの、原価や経費が明らかにされていない。したがって、今回は利益ではなく売上を目的変数とする。
売上を目的変数にするためには、'price', 'discount_amount', 'qty_ordered', 'grand_total'などから売上に相当する列を作る必要がある。
したがってこれらの列を適切に説明変数か目的変数に設定する必要がある。
そのために、以下では不明な'grand_total'の定義を明らかにする。
'''

'\n分析の指針を整理する。\n\n＜目的＞\nデータの分析により、新たな知見を見つけ出し、商品の売り上げを向上させること。\n\n\n＜分析内容＞\n・商品カテゴリーごとの分析\n・支払方法ごとの変化\n・利益が最も大きいカテゴリー\n・顧客分析、ペルソナの考察\n・時期ごとの注文カテゴリの傾向分析\n\nしたがって、下記のような分析が候補として考えられる。\n・売上に影響している要因は何か（回帰）\n・利益を出す商品・出さない商品を予測する（分類）\n・ペルソナの推定（クラスタリング、分類）\n\n今回は特に、「売上に影響している要因は何か（回帰）」に絞って分析を行う。\n'

In [ ]:
cols = ['price', 'discount_amount', 'qty_ordered', 'grand_total']
df2 = df[cols]
df2.head(20)
#このセルの結果より、grand_total = (price - discount_amount) *qty_ordered 
#もしくは grand_total = price * qty_ordered - discount_amount と考えられる。

       price  discount_amount  qty_ordered  grand_total
0    1950.00              0.0          1.0      1950.00
1     240.00              0.0          1.0       240.00
2    2450.00              0.0          1.0      2450.00
3     360.00            300.0          1.0        60.00
4     555.00              0.0          2.0      1110.00
5      80.00              0.0          1.0        80.00
6     360.00            300.0          1.0        60.00
7     170.00              0.0          1.0       170.00
8   96499.00              0.0          1.0     96499.00
9   96499.00              0.0          1.0     96499.00
10   5500.00              0.0          1.0      5500.00
11    210.00              0.0          1.0       366.00
12    156.00              0.0          1.0       366.00
13    120.00              0.0          1.0       120.00
14    320.00              0.0          1.0         0.00
15   1550.00              0.0          1.0      1550.00
16    420.00              0.0          1.0      1270.00
17    360.00              0.0          1.0      1270.00
18    490.00              0.0          1.0      1270.00
19    899.25              0.0          1.0      2118.25

In [ ]:
cheker = df2[(df2['discount_amount'] > 0) & (df2['qty_ordered'] > 2)]
display(cheker)
#このセルの結果より、 grand_total = price * qty_ordered - discount_amount と考えられる。

         price  discount_amount  qty_ordered  grand_total
1287      65.0           195.00          3.0         0.00
1428     151.0           500.00          7.0       557.00
1454     327.0           464.49          3.0       556.00
1456     350.0           500.00          3.0       550.00
1459     350.0           500.00          3.0       550.00
...        ...              ...          ...          ...
583454   795.0           596.25          5.0      3628.75
583481   795.0           485.25          3.0      2999.75
583482   170.0           485.25          5.0      2999.75
583544   166.0           509.55          5.0      3137.45
583568  1420.0           750.00          4.0      5180.00

[10583 rows x 4 columns]

In [ ]:
'''
問題設定「1回の注文時の客単価（grand_total）に影響を与える要因は何か？」

説明変数の列＝['status', 'category_name_1',  'payment_method', 'year', 'month', 'customer_since']
        'grand_total'の計算式に含まれる列や、'grand_total'への影響が極めて小さいと考えられる列は除外した。
        'customer_since'は
        'status'については、以下でその概要を検討する。
目的変数の列＝['grand_total']

        price, qty_ordered, discount_amount を外しているため、モデルの決定係数は低くなる可能性がある。
        したがって、これらを説明変数に含めたモデルとも比較する。
'''

"\n分析に使用する列＝[\n       'item_id', 'sku', 'price', 'qty_ordered', \n       'grand_total', 'category_name_1', 'discount_amount', \n       'payment_method', 'year', 'month', 'customer_since', \n]\n\n念のため残しておく列＝['status', 'increment_id',]\n分析に使用しない列＝['created_at', 'sales_commission_code', 'working_date', 'mv', ]\n\n\n\n        , 'customer_id'\n\n'created_at', 'm_y','fy'→ 文字データでない'year', 'month'のほうが扱いやすいため除外する。時系列は'increment_id'で把握可能。\n'sales_commission_code', 'working_date', 'bi_status',  → データが何を意味するのかが不明かつ、他の列でカバー可能な情報。\n\n\n"